version: "3.9"
services:

  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    command: python /app/manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:5.7
    env_file:
      - .env
    ports:
      - "3302:3306"
    volumes:
      - ./data/mysql/dbb:/var/lib/mysql
  
  
  redis:
    image: redis:7-alpine

  celery:
    build: .
    command: celery -A proj worker -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
      
  celery-beat:
    build: .
    command: celery -A proj beat -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis