# Generated by Django 4.1.3 on 2022-11-22 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('INPROGRESS', 'In progress'), ('DELIVERED', 'Delivered')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_by', to='_auth.customerprofile')),
                ('products', models.ManyToManyField(related_name='order_products', to='core.product')),
                ('resturant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_resturant', to='_auth.resturantprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(related_name='menu_products', to='core.product')),
                ('resturant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_resturant', to='_auth.resturantprofile')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
