# Generated by Django 4.1.3 on 2022-11-22 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ORDERED', 'Ordered'), ('INPROGRESS', 'In progress'), ('DONE', 'Done'), ('WITHDRIVER', 'With Driver'), ('DELIVERED', 'Delivered'), ('CANCELED', 'Cancelled')], default='ORDERED', max_length=50),
        ),
    ]
